name: instagram
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  gradient_text: ^1.0.2
  image_picker: any

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
   - assets/images/placeholder.jpg
   - assets/images/empty.png
   - assets/images/icons/
   - assets/images/search/
   - assets/images/comments/
   - assets/images/posts/post1/
   - assets/images/posts/post2/
   - assets/images/posts/post3/
   - assets/images/posts/post4/
   - assets/images/posts/post5/
   - assets/images/posts/post6/
  fonts:
    - family: Lobster
      fonts:
        - asset: assets/fonts/Lobster-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
